import Head from "next/head";
import Header from "@/components/Header/Header";
import MapContainer from "@/components/Map/MapContainer";
import CssBaseline from "@mui/material/CssBaseline";
import FieldInformation from "@/components/FieldInformation/FieldInformation";

export default function Home() {
  return (
    <>
      <CssBaseline />
      <Head>
        <title>Map Box</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div style={{ height: "100vh" }}>
        <Header />
        <MapContainer />
        <FieldInformation />
      </div>
    </>
  );
}
